### ISSUE TITLE
EMFILE errors and graceful-fs usage

### ISSUE THREAD

**Issue by zachleat** [humanwhocodes/fsx#9]
One of the baseline things I need from an `fs` abstraction is better handling of default `EMFILE` (et al) errors. I typically use https://github.com/isaacs/node-graceful-fs for this, which is just a drop-in replacement for `fs`. It would be nice to be able to pass in `fs` somewhere so that I could integrate with this too (on Node).

**Comment by nzakas** [comment]
In what situations are you typically running into this error? It would be helpful to have some more context because I’ve never run into it personally. Definitely open to adding something for the use case. 

The NodeFsx constructor actually does accept a fs/promises object as an optional argument:
https://github.com/humanwhocodes/fsx/blob/main/packages/node/README.md#usage

It looks like graceful-fs is still using the old callback style of methods, though, so you’d need to promisify the methods to make that work.

**Comment by zachleat** [comment]
I don’t know that I’ve encountered it personally but I’ve had a fair number of folks weigh in with issues related to it on the Eleventy project (mostly Windows users I believe).

If you accept `fs/promises` as an argument, I’d consider this solved well enough for this use case! Feel free to close!

**Comment by nzakas** [comment]
I'm wondering if maybe I should change `NodeFsx` to accept the `fs` module instead? I could still pull the promise-based methods off of `fs.promises` and then if `fs.promises` is undefined, manually promisify the necessary methods. What do you think?

**Comment by nzakas** [comment]
It turns out adding retry was pretty easy:
https://github.com/humanwhocodes/fsx/pull/19

This is just for Node.js, at the moment, but I'll add it to Deno as well.

**Comment by nzakas** [comment]
EMFILE/ENFILE retries are now part of both `fsx-node` and `fsx-deno` as of https://github.com/humanwhocodes/fsx/commit/c2db624f974e111017a3783ac8d4ea9a4a3a87e6, closing.

**Comment by zachleat** [comment]
Amazing!! Sorry for the late reply, I’m OOO this week
